# Highbay二楼工位上较短距离的参数配置文件，主要为增大半径面积。

/**:
  ros__parameters:
    image_topic: image_raw
    camera_info_topic: camera_info
    detection_topic: light_detection
    debug_mask_topic: debug/binary_mask
    publish_debug_mask: true

    light_detector:
      min_hue: 35.0
      max_hue: 95.0
      min_saturation: 45.0
      min_value: 100.0

      min_green_excess: 25.0

      min_area_px2: 1500.0
      min_radius_px: 20.0
      max_radius_px: 30.0
      min_circularity: 0.7
      min_aspect_ratio: 0.75
      max_aspect_ratio: 1.25
      min_fill_ratio: 0.8
      max_fill_ratio: 1.1

      min_inner_brightness: 150.0
      min_contrast_ratio: 10.0

      cleanup:
        close_kernel_size: 3
        close_iterations: 1
        open_kernel_size: 5
        open_iterations: 1
        fill_holes: true
        remove_small_speckle: true
        max_speckle_area_px2: 4.0

    pnp_solver:
      target_radius_m: 0.03
      max_reprojection_error_px: 5.0

    angle_filter:
      process_noise_rad2_per_s: 0.01
      measurement_noise_rad2: 0.0025
      initial_uncertainty_rad2: 0.01
      max_time_step_s: 0.1
